### PR TITLE
AppIcon

### PR DESCRIPTION
**Pull request by sefsh**
It's a ping (pong) icon.

### CODE REVIEW

**Comment by huwr** [comment]
Nicely done! 

Before I merge: where did you find the icon? Did you draw it?

**Comment by sefsh** [comment]
Thanks! Did draw it myself. Did a second, better version of it though, will push. :beers:

**Comment by huwr** [comment]
Sorry about the delay! Definitely prefer the second one!

Much appreciated. :+1:

**Comment by sefsh** [comment]
Yay! You're welcome. :shipit:

**Pull request merged**
